Signatures and Signature verification implemented
W11-Secure-Voting-Solutions/backend pull request #22
Opened 2020-01-22 22:03 UTC by TymoteuszSurynt

Signatures and signature verification implemented

2020-01-22 22:41 UTC, piotrszyma commented on server/apolloassistant/verification.py
> +    h = SHA.new()
Why duplicate?

2020-01-22 22:42 UTC, piotrszyma commented on server/apolloassistant/verification.py
> +    with open(f"{os.getcwd()}/.envs/public_key.pem", "r") as pem_file:
Please don't open file on every call, cache it in memory.

2020-01-22 22:43 UTC, piotrszyma commented on server/apolloassistant/verification.py
> +    with open(f"{os.getcwd()}/.envs/private_key.pem", "r") as pem_file:
Please create `settings.RSA_KEYS_PATH` and setup it relative to `APPS_DIR` and in here use `from django.conf import settings`.

2020-01-23 15:07 UTC, piotrszyma commented
Please update poetry.lock! Probably using `docker-compose exec app poetry update`

2020-01-23 15:42 UTC, rrothenberger requested changes
Please fix failing CI build before merging.

2020-01-23 15:46 UTC, rrothenberger requested changes

2020-01-23 15:46 UTC, rafalrothenberger commented on server/config/settings/base.py
> +PRIVATE_KEY = None
Add it to production config as well. And do not use paths out of server directory.

2020-01-23 18:19 UTC, rrothenberger approved these changes

2020-01-23 18:19 UTC, merged